### ISSUE TITLE
Maintainer on Packagist

### ISSUE THREAD

**Issue by stof** [minkphp/MinkWUnitDriver#8]
@patrickdreyer currently, you are the only guy with maintainer access to this package on Packagist. given that you are not really active anymore on the driver, could you add me as a Packagist maintainer as well ?

**Comment by patrickdreyer** [comment]
@stof
Just tried to add you as a maintainer and saw, that you could somehow 
manage it yourself.
Is this correct?
Sorry for my late answer.
There is an error on github, so that I could not answer within github.

Am 06.01.2015 um 02:07 schrieb Christophe Coevoet:

> @patrickdreyer https://github.com/patrickdreyer currently, you are 
> the only guy with maintainer access to this package on Packagist. 
> given that you are not really active anymore on the driver, could you 
> add me as a Packagist maintainer as well ?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/Behat/MinkWUnitDriver/issues/8.

## 

_Patrick Dreyer_
Weidstrasse 35
8932 Mettmenstetten

Mobile: +41 (76) 711 66 68 callto:+41767116668
Fix: +41 (43) 443 55 75 callto:+41434435575
Skype: PatrickDreyer skype:PatrickDreyer?call

XING https://www.xing.com/profile/Patrick_Dreyer, LinkedIn 
http://ch.linkedin.com/pub/patrick-dreyer/18/52/834

**Comment by stof** [comment]
Yah, I asked Jordi to add me as an maintainer on Packagist to be able to complete the organization migration as there was no answer here at this time, and I forgot to close this issue when he did it.
